config/routes.rb
Rails.application.routes.draw do
  root to: 'chatrooms#index'
  
  resources :chatrooms, only: [:create, :show, :index, :new]
  resources :messages, only: [:create]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :chatrooms, through: :messages
  # validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.new(params.require(:chatroom).permit(:topic))

    if @chatroom.save
      redirect_to chatrooms_path
    else
      redirect_to chatrooms_path
    end
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.new(message_params)
    message.user = current_user

    if message.save!
      ActionCable.server.broadcast 'messages',
        message: message.text,
        user: message.user.email
      head :ok
    else
      redirect_to chatrooms_path
    end
  end

  private 
  
  def message_params
    params.require(:message).permit(:text, :chatroom_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chatrooms/index.html.erb
<h1>Chatrooms</h1>
<%= link_to  "Create a Chatroom", new_chatroom_path %>
<ul>
  <% @chatrooms.each do |chatroom| %>
    <li>
      <%= link_to  chatroom.topic , chatroom_path(chatroom.id) %>
    </li>
  <% end %>
</ul>

app/views/chatrooms/new.html.erb
<%= form_for( @chatroom) do |f| %>
  <%= f.label :topic %>
  <%= f.text_field :topic %>

  <br>
  <%= f.submit "Submit"%>
<% end %>

app/views/chatrooms/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1><%= @chatroom.topic %></h1>

<div class="panel panel-default">
  <% if @chatroom.messages.any? %>
    <div class="panel-body" id="messages">
      <%= render partial: 'messages/message', collection: @chatroom.messages%>
    </div>
  <%else%>
    <div class="panel-body hidden" id="messages">
    </div>
  <%end%>
</div>

  <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<%
=begin%>
 <%= collection.each do |message| %>
  <p> <b>message.user.email</b> message.text</p>
<% end %> 
<%
=end%>

<p> <b><%= message.user.email %></b> <%= message.text%></p>

app/views/messages/_message_form.html.erb
<%= form_for message, remote: true, authenticity_token: true do |f| %>
  <%= f.label :your_message %>:
  <%= f.text_area :text, class: "form-control", data: {textarea: "message"} %>

  <%= f.hidden_field :chatroom_id, value: chatroom.id %>
  <%= f.submit "send", class: "btn btn-primary", data: {send: "message"} %>
<% end %>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>